# Generated by Django 5.0.1 on 2024-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='upload in 198x148 pixel resolution', max_length=150),
        ),
    ]
