# Generated by Django 5.0.1 on 2024-04-04 00:17

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_small_description_remove_product_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='upload in 198x148', null=True, upload_to=store.models.get_file_path),
        ),
    ]
